### ISSUE TITLE
เมื่อเลือกหนังใหม่ แล้วใส่เลขตัวแรก ไม่คำนวนราคาให้ในบางครั้ง

### ISSUE THREAD

**Issue by naruepat** [nuntjw/thinknet-exercise#1]
VDO
[https://photos.app.goo.gl/axXZn06uJ7ceryHz1](url)

ถ้าแก้ไขเสร็จแล้วฝากตอบมาใน issue นี้ให้ด้วยนะครับ

**Comment by nuntjw** [comment]
ลองแก้ดูแล้วนะครับ
สามารถเข้าหน้าเว็บล่าสุดได้ที่ https://thinknet-movie-ticket-machine.firebaseapp.com/ ครับ

**Comment by naruepat** [comment]
โอเคเลยครับ
