### ISSUE TITLE
อยากให้แสดงผล Your Ticket เป็นหน้าใหม่

### ISSUE THREAD

**Issue by naruepat** [nuntjw/thinknet-exercise#2]
![screenshot-localhost-3001-2018 05 14-11-22-01](https://user-images.githubusercontent.com/5475736/39978168-376da902-5769-11e8-8207-23506dc2ad60.png)

จากเดิมเมื่อกดปุ่ม Buy จะแสดงข้อมูล Your Ticket แล้ว แต่อยากให้เมื่อกดปุ่ม Buy แล้วแสดง (กรอบสีแดง) เป็นหน้าใหม่ พร้อมมีปุ่ม Back เพื่อกลับไปหน้าเลือกซื้อตั๋วใหม่ได้

**Comment by nuntjw** [comment]
@naruepat เพิ่ม Routing สำหรับแสดงผลข้อมูลตั๋วหนังกับเงินทอนแล้วครับ

**Comment by naruepat** [comment]
เยี่ยมเลยครับ
